# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='discussions',
            field=models.ManyToManyField(blank=True, to='tracker.Discussion', verbose_name=b'discussion timeline'),
        ),
    ]
