# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20160625_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
    ]
