# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 15:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0003_event_ispublic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='isPermanent',
            field=models.BooleanField(default=False, verbose_name=b'keep this event forever'),
        ),
        migrations.AlterField(
            model_name='event',
            name='isPublic',
            field=models.BooleanField(default=False, verbose_name=b'share this event with other users'),
        ),
        migrations.AddField(
            model_name='pin',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Event'),
        ),
        migrations.AddField(
            model_name='pin',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
