# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20160627_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
