# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_discussion_createddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('validDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='validDate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='discussions',
        ),
        migrations.AddField(
            model_name='event',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'end date (only used if start date is defined)'),
        ),
        migrations.AddField(
            model_name='event',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'start date (if blank, event time range is defined by that of threads'),
        ),
        migrations.AddField(
            model_name='thread',
            name='discussions',
            field=models.ManyToManyField(blank=True, to='tracker.Discussion'),
        ),
        migrations.AddField(
            model_name='event',
            name='threads',
            field=models.ManyToManyField(blank=True, to='tracker.Thread'),
        ),
    ]
