# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-24 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='isExtensible',
            field=models.BooleanField(default=True),
        ),
    ]
